export const INIT_TODO = 'INIT_TODO'
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const TOOGLE_TODO = 'TOOGLE_TODO'
export const TOOGLE_ALL = 'TOOGLE_ALL'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'